class AddColumnToMitsumoris < ActiveRecord::Migration
  def change
      add_column :mitsumoris, :konyuRirekiId, :integer
      add_column :mitsumoris, :mitsumoriNo, :integer
      add_column :mitsumoris, :COL1_1, :integer
      add_column :mitsumoris, :COL2_1, :integer
      add_column :mitsumoris, :COL3_1, :integer
      add_column :mitsumoris, :COL3_2, :integer
      add_column :mitsumoris, :COL3_3, :integer
      add_column :mitsumoris, :COL3_4, :integer
      add_column :mitsumoris, :COL3_5, :integer
      add_column :mitsumoris, :COL3_6, :integer
      add_column :mitsumoris, :COL3_7, :integer
      add_column :mitsumoris, :COL3_8, :integer
      add_column :mitsumoris, :COL3_9, :integer
      add_column :mitsumoris, :COL3_10, :integer
      add_column :mitsumoris, :COL3_11, :integer
      add_column :mitsumoris, :COL3_12, :integer
      add_column :mitsumoris, :COL3_13, :integer
      add_column :mitsumoris, :COL4_1, :integer
      add_column :mitsumoris, :COL5_1, :integer
      add_column :mitsumoris, :COL5_2, :integer
      add_column :mitsumoris, :COL5_3, :integer
      add_column :mitsumoris, :COL5_4, :integer
      add_column :mitsumoris, :COL6_1, :integer
      add_column :mitsumoris, :COL7_1, :integer
      add_column :mitsumoris, :COL7_2, :integer
      add_column :mitsumoris, :COL7_3, :integer
      add_column :mitsumoris, :COL7_4, :integer
      add_column :mitsumoris, :COL7_5, :integer
      add_column :mitsumoris, :COL7_6, :integer
      add_column :mitsumoris, :COL7_7, :integer
      add_column :mitsumoris, :COL8_1, :integer
      add_column :mitsumoris, :COL8_2, :integer
      add_column :mitsumoris, :COL8_3, :integer
      add_column :mitsumoris, :COL9_1, :integer
      add_column :mitsumoris, :COL9_2, :integer
      add_column :mitsumoris, :COL9_3, :integer
      add_column :mitsumoris, :COL10_1, :integer
      add_column :mitsumoris, :COL10_2, :integer
      add_column :mitsumoris, :COL10_3, :integer
      add_column :mitsumoris, :COL10_4, :integer
      add_column :mitsumoris, :COL11_1, :integer
      add_column :mitsumoris, :COL11_2, :integer
      add_column :mitsumoris, :COL11_3, :integer
      add_column :mitsumoris, :COL11_4, :integer
      add_column :mitsumoris, :COL12_1, :integer
      add_column :mitsumoris, :COL13_1, :integer
      add_column :mitsumoris, :COL13_2, :integer
      add_column :mitsumoris, :COL13_3, :integer
      add_column :mitsumoris, :COL13_4, :integer
      add_column :mitsumoris, :COL13_5, :integer
      add_column :mitsumoris, :COL14_1, :integer
      add_column :mitsumoris, :COL14_2, :integer
      add_column :mitsumoris, :COL15_1, :integer
      add_column :mitsumoris, :COL16_1, :integer
      add_column :mitsumoris, :COL16_2, :integer
      add_column :mitsumoris, :COL16_3, :integer
      add_column :mitsumoris, :COL16_4, :integer
      add_column :mitsumoris, :COL16_5, :integer
      add_column :mitsumoris, :COL16_6, :integer
      add_column :mitsumoris, :COL16_7, :integer
      add_column :mitsumoris, :COL16_8, :integer
      add_column :mitsumoris, :COL16_9, :integer
      add_column :mitsumoris, :COL16_10, :integer
      add_column :mitsumoris, :COL16_11, :integer
      add_column :mitsumoris, :COL16_12, :integer
      add_column :mitsumoris, :COL16_13, :integer
      add_column :mitsumoris, :COL17_1, :integer
      add_column :mitsumoris, :COL17_2, :integer
      add_column :mitsumoris, :COL17_3, :integer
      add_column :mitsumoris, :COL17_4, :integer
      add_column :mitsumoris, :COL17_5, :integer
      add_column :mitsumoris, :COL17_6, :integer
      add_column :mitsumoris, :COL17_7, :integer
      add_column :mitsumoris, :COL17_8, :integer
      add_column :mitsumoris, :COL17_9, :integer
      add_column :mitsumoris, :COL17_10, :integer
      add_column :mitsumoris, :COL17_11, :integer
      add_column :mitsumoris, :COL17_12, :integer
      add_column :mitsumoris, :COL17_13, :integer
      add_column :mitsumoris, :COL17_14, :integer
      add_column :mitsumoris, :COL17_15, :integer
      add_column :mitsumoris, :COL18_1, :integer
      add_column :mitsumoris, :COL18_2, :integer
      add_column :mitsumoris, :COL18_3, :integer
      add_column :mitsumoris, :COL18_4, :integer
      add_column :mitsumoris, :COL18_5, :integer
      add_column :mitsumoris, :COL18_6, :integer
      add_column :mitsumoris, :COL18_7, :integer
      add_column :mitsumoris, :COL18_8, :integer
      add_column :mitsumoris, :COL19_1, :integer
      add_column :mitsumoris, :COL19_2, :integer
      add_column :mitsumoris, :COL19_3, :integer
      add_column :mitsumoris, :COL19_4, :integer
      add_column :mitsumoris, :COL19_5, :integer
      add_column :mitsumoris, :COL19_6, :integer
      add_column :mitsumoris, :COL19_7, :integer
      add_column :mitsumoris, :COL19_8, :integer
      add_column :mitsumoris, :COL19_9, :integer
      add_column :mitsumoris, :COL19_10, :integer
      add_column :mitsumoris, :COL19_11, :integer
      add_column :mitsumoris, :COL19_12, :integer
      add_column :mitsumoris, :COL19_13, :integer
      add_column :mitsumoris, :COL19_14, :integer
      add_column :mitsumoris, :COL19_15, :integer
      add_column :mitsumoris, :COL19_16, :integer
      add_column :mitsumoris, :COL19_17, :integer
      add_column :mitsumoris, :COL19_18, :integer
      add_column :mitsumoris, :COL19_19, :integer
      add_column :mitsumoris, :COL20_1, :integer
      add_column :mitsumoris, :COL20_2, :integer
      add_column :mitsumoris, :COL20_3, :integer
      add_column :mitsumoris, :COL20_4, :integer
      add_column :mitsumoris, :COL20_5, :integer
      add_column :mitsumoris, :COL20_6, :integer
      add_column :mitsumoris, :COL20_7, :integer
      add_column :mitsumoris, :COL20_8, :integer
      add_column :mitsumoris, :COL20_9, :integer
      add_column :mitsumoris, :COL20_10, :integer
      add_column :mitsumoris, :COL20_11, :integer
      add_column :mitsumoris, :COL20_12, :integer
      add_column :mitsumoris, :COL21_1, :integer
      add_column :mitsumoris, :COL21_2, :integer
      add_column :mitsumoris, :COL21_3, :integer
      add_column :mitsumoris, :COL21_4, :integer
      add_column :mitsumoris, :COL21_5, :integer
      add_column :mitsumoris, :COL21_6, :integer
      add_column :mitsumoris, :COL22_1, :integer
      add_column :mitsumoris, :COL22_2, :integer
      add_column :mitsumoris, :COL22_3, :integer
      add_column :mitsumoris, :COL_23_1, :integer
      add_column :mitsumoris, :COL23_2, :integer
      add_column :mitsumoris, :COL23_3, :integer
      add_column :mitsumoris, :COL23_4, :integer
      add_column :mitsumoris, :COL23_5, :integer
      add_column :mitsumoris, :COL23_6, :integer
      add_column :mitsumoris, :COL24_1, :integer
      add_column :mitsumoris, :COL24_2, :integer
      add_column :mitsumoris, :COL24_3, :integer
      add_column :mitsumoris, :COL24_4, :integer
      add_column :mitsumoris, :COL24_5, :integer
      add_column :mitsumoris, :COL24_6, :integer
      add_column :mitsumoris, :COL24_7, :integer
      add_column :mitsumoris, :COL24_8, :integer
      add_column :mitsumoris, :COL24_9, :integer
      add_column :mitsumoris, :COL25_1, :integer
      add_column :mitsumoris, :torokushaId, :integer
      add_column :mitsumoris, :koshinshaId, :integer
  end
end
